// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_Hnp0k5A8FnlcpFKsxXfzFaxqyOhVtA',
    appId: '1:983046182959:web:f3690c13fb6d4e47414eda',
    messagingSenderId: '983046182959',
    projectId: 'chat-app-f4264',
    authDomain: 'chat-app-f4264.firebaseapp.com',
    storageBucket: 'chat-app-f4264.firebasestorage.app',
    measurementId: 'G-1RYPXNDKTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnytZgboR9x-jBC_mu_3Y-kinIwTLIew0',
    appId: '1:983046182959:android:e2fd12c6b29209b6414eda',
    messagingSenderId: '983046182959',
    projectId: 'chat-app-f4264',
    storageBucket: 'chat-app-f4264.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIzf3lT8bRajNpkp0M4wp5rWTY_kGIdY',
    appId: '1:983046182959:ios:242061b275caf40a414eda',
    messagingSenderId: '983046182959',
    projectId: 'chat-app-f4264',
    storageBucket: 'chat-app-f4264.firebasestorage.app',
    iosBundleId: 'com.example.scholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcIzf3lT8bRajNpkp0M4wp5rWTY_kGIdY',
    appId: '1:983046182959:ios:242061b275caf40a414eda',
    messagingSenderId: '983046182959',
    projectId: 'chat-app-f4264',
    storageBucket: 'chat-app-f4264.firebasestorage.app',
    iosBundleId: 'com.example.scholar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT_Hnp0k5A8FnlcpFKsxXfzFaxqyOhVtA',
    appId: '1:983046182959:web:7caba2f9bfcf9e3f414eda',
    messagingSenderId: '983046182959',
    projectId: 'chat-app-f4264',
    authDomain: 'chat-app-f4264.firebaseapp.com',
    storageBucket: 'chat-app-f4264.firebasestorage.app',
    measurementId: 'G-WWT2SJFQCH',
  );
}
